# Generated by Django 6.0.2 on 2026-02-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_alter_show_options_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ['date', 'time'], 'verbose_name': 'Función', 'verbose_name_plural': 'Funciones'},
        ),
        migrations.AlterField(
            model_name='showseat',
            name='reserved_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
