# Generated by Django 5.0.7 on 2026-03-09 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_producto_combo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='combo',
            old_name='precio',
            new_name='precio_combo',
        ),
    ]
