# Generated by Django 5.0.7 on 2026-03-09 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_rename_precio_combo_precio_combo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='combo',
            old_name='precio_combo',
            new_name='precio',
        ),
    ]
