# Generated by Django 5.0.7 on 2026-03-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0013_ventaproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaproducto',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
