# Generated by Django 5.0.7 on 2026-03-12 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0014_alter_ventaproducto_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaproducto',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema.producto'),
        ),
    ]
