# Generated by Django 5.0.7 on 2026-03-12 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_remove_combo_activo_ventaproducto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VentaProducto',
            new_name='VentaProductoLocal',
        ),
    ]
